# Generated by Django 5.2.11 on 2026-10-04 17:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0018_order_shipping_cost_before_promotion_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrowserEventReceipt",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Consent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("accepted", models.BooleanField(default=False)),
                ("revision", models.PositiveIntegerField(default=1)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expires_at", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="MetaPurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("consent_revision", models.PositiveIntegerField()),
                ("event_id", models.CharField(max_length=80, unique=True)),
                ("occurred_at", models.DateTimeField()),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("sending", "En envío"),
                            ("sent", "Recibido por Meta"),
                            ("failed", "Revisar"),
                            ("expired", "Vencido"),
                            ("cancelled", "Consentimiento retirado"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("payload", models.JSONField(default=dict)),
                ("pixel_id", models.CharField(max_length=30)),
                ("graph_version", models.CharField(max_length=15)),
                (
                    "test_event_code",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                (
                    "next_attempt_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("claim_id", models.UUIDField(editable=False, null=True)),
                ("claim_expires_at", models.DateTimeField(null=True)),
                ("sent_at", models.DateTimeField(null=True)),
                (
                    "diagnostic",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("payload_purged_at", models.DateTimeField(null=True)),
                (
                    "consent",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="marketing.consent",
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="orders.order"
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
