"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import sys
import logging

from dotenv import load_dotenv
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Carga variables de entorno desde .env si existe (no se commitea)
load_dotenv(BASE_DIR.parent / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

SECRET_KEY = os.getenv("SECRET_KEY", "change-me-in-prod-debug-enabled-temporarily")
DEBUG = os.getenv("DEBUG", "0") == "1"


ALLOWED_HOSTS = [
    h.strip()
    for h in os.getenv("ALLOWED_HOSTS", "127.0.0.1,localhost").split(",")
    if h.strip()
]

# Agregar el host de SITE_URL automáticamente (útil para túneles cloudflared/ngrok y Render)
_site_url = os.getenv("SITE_URL", "")
if _site_url:
    from urllib.parse import urlparse as _urlparse

    _site_host = _urlparse(_site_url).hostname
    if _site_host and _site_host not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(_site_host)

# Render y cloudflared sirven sobre HTTPS — necesario para forms + CSRF
if _site_url.startswith("https"):
    CSRF_TRUSTED_ORIGINS = [_site_url]
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Feature flag: MercadoPago apagado por defecto (la web cobra solo por transferencia).
# Para reactivarlo en el futuro: setear MP_ENABLED=1 (y tener MP_ACCESS_TOKEN +
# MP_WEBHOOK_SECRET productivos). El código de MP queda intacto, solo dormido.
MP_ENABLED = os.getenv("MP_ENABLED", "0") == "1"

# Datos bancarios para el pago por transferencia (no hardcodear en el repo).
# Cargar en variables de entorno: BANK_HOLDER, BANK_ALIAS, BANK_CBU, BANK_NAME.
BANK_TRANSFER = {
    "holder": os.getenv("BANK_HOLDER", "").strip(),
    "alias": os.getenv("BANK_ALIAS", "").strip(),
    "cbu": os.getenv("BANK_CBU", "").strip(),
    "bank": os.getenv("BANK_NAME", "").strip(),
}

if DEBUG and MP_ENABLED and not os.getenv("MP_ACCESS_TOKEN"):
    print(
        "[WARN] MP_ACCESS_TOKEN no está configurado (sandbox MercadoPago no funcionará)."
    )

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Apps del proyecto
    "shop",
    "cart",
    "orders",
    "payments",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # <-- agregar acá
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR.parent / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "cart.context_processors.cart",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Configure database from DATABASE_URL, fallback to SQLite when parsing fails.
# conn_health_checks: Neon (Postgres serverless) cierra conexiones inactivas;
# con health checks Django descarta la conexión muerta y reabre en vez de fallar.
_db_config = dj_database_url.config(conn_max_age=600, conn_health_checks=True)
if not _db_config or not _db_config.get("ENGINE"):
    _db_config = {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": str(BASE_DIR / "db.sqlite3"),
    }

DATABASES = {"default": _db_config}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR.parent / "static"]

# Storage backends (Django 5 STORAGES dict).
# - staticfiles: WhiteNoise (comprimido + manifest) en prod.
# - default (media): Cloudflare R2 si está configurado; si no, filesystem local.
# En tests usamos storage simple (sin manifest) para no depender de collectstatic.
if "test" in sys.argv:
    _WHITENOISE_STATIC = {"BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage"}
else:
    _WHITENOISE_STATIC = {"BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage"}

R2_BUCKET_NAME = os.getenv("R2_BUCKET_NAME", "").strip()
if R2_BUCKET_NAME:
    AWS_ACCESS_KEY_ID = os.getenv("R2_ACCESS_KEY_ID", "")
    AWS_SECRET_ACCESS_KEY = os.getenv("R2_SECRET_ACCESS_KEY", "")
    AWS_STORAGE_BUCKET_NAME = R2_BUCKET_NAME
    AWS_S3_ENDPOINT_URL = os.getenv("R2_ENDPOINT_URL", "")  # https://<account>.r2.cloudflarestorage.com
    AWS_S3_REGION_NAME = "auto"
    AWS_S3_SIGNATURE_VERSION = "s3v4"
    AWS_DEFAULT_ACL = None
    AWS_QUERYSTRING_AUTH = False
    AWS_S3_FILE_OVERWRITE = False
    # Dominio público para servir las imágenes (pub-xxxx.r2.dev o dominio propio).
    AWS_S3_CUSTOM_DOMAIN = os.getenv("R2_PUBLIC_DOMAIN", "").strip() or None
    # boto3 >= 1.36 manda checksums CRC32 por defecto que R2 rechaza en el PUT
    # (Server Error 500 al subir). Los pedimos solo cuando son necesarios.
    from botocore.config import Config as _BotoConfig

    AWS_S3_CLIENT_CONFIG = _BotoConfig(
        signature_version="s3v4",
        request_checksum_calculation="when_required",
        response_checksum_validation="when_required",
    )
    STORAGES = {
        "default": {"BACKEND": "storages.backends.s3.S3Storage"},
        "staticfiles": _WHITENOISE_STATIC,
    }
else:
    STORAGES = {
        "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
        "staticfiles": _WHITENOISE_STATIC,
    }

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

MEDIA_URL = "/media/"
# Por defecto usar el directorio `media/` en la raíz del repositorio (un nivel arriba de `backend`)
MEDIA_ROOT = Path(os.getenv("MEDIA_ROOT", str(BASE_DIR.parent / "media")))
MEDIA_ROOT = Path(MEDIA_ROOT)
SERVE_MEDIA = DEBUG or os.getenv("SERVE_MEDIA", "0") == "1"
RUNNING_TESTS = "test" in sys.argv

# Crear directorio de media por defecto cuando se sirve media desde la app
if SERVE_MEDIA:
    try:
        MEDIA_ROOT.mkdir(parents=True, exist_ok=True)
    except Exception:
        logging.getLogger("config.settings").warning(
            "No se pudo crear MEDIA_ROOT: %s", MEDIA_ROOT
        )

if not DEBUG and not RUNNING_TESTS:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = int(os.getenv("SECURE_HSTS_SECONDS", "31536000"))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"
    X_FRAME_OPTIONS = "DENY"


LOG_LEVEL = os.getenv("LOG_LEVEL", "INFO").upper()

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "structured": {
            "format": "%(asctime)s level=%(levelname)s logger=%(name)s module=%(module)s msg=%(message)s",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "structured",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": LOG_LEVEL,
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "payments": {
            "handlers": ["console"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "orders": {
            "handlers": ["console"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
    },
}

# Email (Brevo SMTP). Si hay credenciales SMTP usamos Brevo; si no, consola (dev).
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "RaSel <no-reply@rasel.local>")
ORDER_NOTIFICATION_EMAIL = os.getenv("ORDER_NOTIFICATION_EMAIL", "").strip()

EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "").strip()
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "").strip()

if EMAIL_HOST_USER and EMAIL_HOST_PASSWORD:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp-relay.brevo.com")
    EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
    EMAIL_USE_TLS = True
else:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

SENTRY_DSN = os.getenv("SENTRY_DSN", "").strip()
if SENTRY_DSN and not RUNNING_TESTS:
    try:
        import sentry_sdk
        from sentry_sdk.integrations.django import DjangoIntegration

        sentry_sdk.init(
            dsn=SENTRY_DSN,
            integrations=[DjangoIntegration()],
            traces_sample_rate=float(os.getenv("SENTRY_TRACES_SAMPLE_RATE", "0.0")),
            send_default_pii=False,
            environment=os.getenv(
                "SENTRY_ENVIRONMENT", "development" if DEBUG else "production"
            ),
        )
    except Exception as exc:
        logging.getLogger("config.settings").warning(
            "No se pudo inicializar Sentry: %s", exc
        )
