# Generated by Django 5.2.11 on 2026-02-26 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_mp_payment_id_order_mp_preference_id_and_more"),
        ("shop", "0002_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_items",
                to="shop.variant",
            ),
        ),
    ]
