# Generated by Django 6.0.3 on 2026-03-06 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_orderitem_variant"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(default="mp", max_length=20),
        ),
    ]
