# Generated by Django 6.0.3 on 2026-06-20 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_confirmation_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='stock_restored',
            field=models.BooleanField(default=False),
        ),
    ]
