# Generated by Django 6.0.3 on 2026-06-23 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_paid_email_sent_order_stock_restored'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_zone',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
