# Generated by Django 6.0.3 on 2026-06-23 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_shipping_cost_order_shipping_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_carrier_arranged',
            field=models.BooleanField(default=False),
        ),
    ]
