# Generated by Django 6.0.3 on 2026-07-05 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_carrier_arranged'),
        ('shipping', '0007_pickuppoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('ship', 'Envío a domicilio'), ('pickup', 'Retiro en punto de retiro')], default='ship', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='shipping.pickuppoint'),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_point_label',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='order',
            name='address_line',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='postal_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
