# Generated by Django 6.0.3 on 2026-07-09 20:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_delivery_method_order_pickup_point_and_more'),
        ('shipping', '0009_alter_pickuppoint_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'orden', 'verbose_name_plural': 'órdenes'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'ítem', 'verbose_name_plural': 'ítems'},
        ),
        migrations.AlterField(
            model_name='order',
            name='address_line',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='dirección'),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='ciudad'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('ship', 'Envío a domicilio'), ('pickup', 'Retiro en punto de retiro')], default='ship', max_length=10, verbose_name='entrega'),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='order',
            name='full_name',
            field=models.CharField(max_length=120, verbose_name='nombre y apellido'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('transfer', 'Transferencia'), ('cod', 'Efectivo (contraentrega)'), ('mp', 'MercadoPago')], default='mp', max_length=20, verbose_name='método de pago'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='teléfono'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pickup_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='shipping.pickuppoint', verbose_name='punto de retiro'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pickup_point_label',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='punto de retiro (histórico)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='postal_code',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='código postal'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_carrier_arranged',
            field=models.BooleanField(default=False, verbose_name='correo a cargo del comprador'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='costo de envío'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_zone',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='zona de envío'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagada'), ('shipped', 'Enviada'), ('cancelled', 'Cancelada')], default='pending', max_length=20, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='order',
            name='stock_restored',
            field=models.BooleanField(default=False, verbose_name='stock repuesto'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='total'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='line_total',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='subtotal'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_name',
            field=models.CharField(max_length=150, verbose_name='producto'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='cantidad'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='precio unitario'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='variant_name',
            field=models.CharField(max_length=80, verbose_name='variante'),
        ),
    ]
