# Generated by Django 6.0.3 on 2026-07-12 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_order_options_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipped_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
