# Generated by Django 6.0.3 on 2026-07-12 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_shipped_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address_extra',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='piso / depto / info adicional'),
        ),
    ]
