# Generated by Django 5.2.11 on 2026-08-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0013_order_payment_state_and_mp_constraints"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_discount_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                verbose_name="descuento por medio de pago",
            ),
        ),
    ]
