# Generated by Django 5.2.11 on 2026-09-16 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0016_separate_payment_and_fulfillment"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="analytics_attributed_at",
            field=models.DateTimeField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="analytics_attribution",
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
    ]
