# Generated by Django 6.0.3 on 2026-06-23 01:40

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text="Identificador interno, ej. 'free', 'amba', 'national'.", max_length=40, unique=True)),
                ('name', models.CharField(help_text="Ej. 'CABA y Moreno'.", max_length=80)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Costo del envío. 0 = gratis.', max_digits=12)),
                ('description', models.TextField(blank=True, default='', help_text='Texto que se muestra en la página de envíos.')),
                ('is_default', models.BooleanField(default=False, help_text='Se aplica cuando el CP no cae en ninguna regla (resto del país).')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=100, help_text='Orden de prioridad. Menor gana ante rangos superpuestos.')),
            ],
            options={
                'verbose_name': 'Zona de envío',
                'verbose_name_plural': 'Zonas de envío',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PostalCodeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cp_from', models.PositiveIntegerField(help_text='CP inicial del rango (inclusive).')),
                ('cp_to', models.PositiveIntegerField(help_text='CP final del rango (inclusive).')),
                ('note', models.CharField(blank=True, default='', help_text="Referencia, ej. 'CABA', 'Moreno', 'Conurbano'.", max_length=120)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='shipping.shippingzone')),
            ],
            options={
                'verbose_name': 'Regla de código postal',
                'verbose_name_plural': 'Reglas de código postal',
                'ordering': ['cp_from', 'cp_to'],
            },
        ),
    ]
