# Generated by Django 6.0.3 on 2026-06-23 02:36

from decimal import Decimal
from django.db import migrations, models


DEFAULT_FREE_OVER = Decimal("30000.00")


def seed_threshold(apps, schema_editor):
    """
    La zona gratis (CABA + Moreno) pasa a tener envío gratis solo desde un
    mínimo de compra. Por debajo, cobra como AMBA: copiamos el precio AMBA
    vigente en esta DB (queda como monto fijo independiente, editable luego).
    """
    ShippingZone = apps.get_model("shipping", "ShippingZone")
    free = ShippingZone.objects.filter(code="free").first()
    if not free:
        return
    amba = ShippingZone.objects.filter(code="amba").first()
    fallback = amba.price if amba else Decimal("0.00")

    free.free_over = DEFAULT_FREE_OVER
    free.below_min_price = fallback
    free.save(update_fields=["free_over", "below_min_price"])


def unseed_threshold(apps, schema_editor):
    ShippingZone = apps.get_model("shipping", "ShippingZone")
    ShippingZone.objects.filter(code="free").update(
        free_over=None, below_min_price=Decimal("0.00")
    )


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0003_fix_zone_boundaries'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingzone',
            name='below_min_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Costo de envío cuando el subtotal no alcanza el mínimo ('Free over'). Solo aplica si 'Free over' está seteado.", max_digits=12),
        ),
        migrations.AddField(
            model_name='shippingzone',
            name='free_over',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Envío gratis a partir de este subtotal de compra. Vacío = siempre gratis (sin mínimo).', max_digits=12, null=True),
        ),
        migrations.RunPython(seed_threshold, unseed_threshold),
    ]
