# Generated by Django 6.0.3 on 2026-06-23 12:04

from django.db import migrations, models


LEGEND = (
    "Los envíos se realizan a través de la empresa de correo que el comprador "
    "elija. RaSel se encarga de acercar el pedido sin costo adicional hasta la "
    "sucursal de CABA de la empresa seleccionada y el comprador se hace cargo "
    "del costo del envío. El seguro, los tiempos y condiciones del correo son "
    "responsabilidad de la empresa seleccionada."
)

OLD_DESCRIPTION = (
    "Resto del país. El envío se gestiona a través de encomiendas de correo "
    "con un valor fijo."
)


def enable_carrier_arranged(apps, schema_editor):
    """
    La zona 'resto del país' deja de cobrar un valor fijo: el envío queda a
    cargo del comprador. Activamos el flag y cargamos la leyenda en description.
    """
    ShippingZone = apps.get_model("shipping", "ShippingZone")
    national = ShippingZone.objects.filter(code="national").first()
    if not national:
        return
    national.carrier_arranged = True
    national.description = LEGEND
    national.save(update_fields=["carrier_arranged", "description"])


def revert_carrier_arranged(apps, schema_editor):
    ShippingZone = apps.get_model("shipping", "ShippingZone")
    ShippingZone.objects.filter(code="national").update(
        carrier_arranged=False, description=OLD_DESCRIPTION
    )


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0004_free_shipping_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingzone',
            name='carrier_arranged',
            field=models.BooleanField(default=False, help_text="El comprador elige y paga el correo; RaSel no cobra el envío (lo lleva a la sucursal de CABA). Si está activo, se ignoran 'Price' y 'Free over' y se muestra la leyenda de 'Description'."),
        ),
        migrations.RunPython(enable_carrier_arranged, revert_carrier_arranged),
    ]
