# Generated by Django 6.0.3 on 2026-07-05 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0006_cod_allowed'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Ej. 'Punto de retiro CABA'.", max_length=80)),
                ('address', models.CharField(help_text='Dirección completa del punto.', max_length=200)),
                ('schedule_notes', models.TextField(blank=True, default='', help_text='Horarios o indicaciones para el retiro (se muestran en el checkout).')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=100)),
            ],
            options={
                'verbose_name': 'Punto de retiro',
                'verbose_name_plural': 'Puntos de retiro',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
