# Generated by Django 6.0.3 on 2026-07-09 20:42

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0008_seed_pickup_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickuppoint',
            name='address',
            field=models.CharField(help_text='Dirección completa del punto.', max_length=200, verbose_name='dirección'),
        ),
        migrations.AlterField(
            model_name='pickuppoint',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='activo'),
        ),
        migrations.AlterField(
            model_name='pickuppoint',
            name='name',
            field=models.CharField(help_text="Ej. 'Punto de retiro CABA'.", max_length=80, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='pickuppoint',
            name='schedule_notes',
            field=models.TextField(blank=True, default='', help_text='Horarios o indicaciones para el retiro (se muestran en el checkout).', verbose_name='horarios e indicaciones'),
        ),
        migrations.AlterField(
            model_name='pickuppoint',
            name='sort_order',
            field=models.PositiveIntegerField(default=100, verbose_name='prioridad'),
        ),
        migrations.AlterField(
            model_name='postalcoderule',
            name='cp_from',
            field=models.PositiveIntegerField(help_text='CP inicial del rango (inclusive).', verbose_name='CP desde'),
        ),
        migrations.AlterField(
            model_name='postalcoderule',
            name='cp_to',
            field=models.PositiveIntegerField(help_text='CP final del rango (inclusive).', verbose_name='CP hasta'),
        ),
        migrations.AlterField(
            model_name='postalcoderule',
            name='note',
            field=models.CharField(blank=True, default='', help_text="Referencia, ej. 'CABA', 'Moreno', 'Conurbano'.", max_length=120, verbose_name='referencia'),
        ),
        migrations.AlterField(
            model_name='postalcoderule',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='shipping.shippingzone', verbose_name='zona'),
        ),
        migrations.AlterField(
            model_name='shippingzone',
            name='below_min_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Costo de envío cuando el subtotal no alcanza el mínimo ('Gratis desde'). Solo aplica si 'Gratis desde' está seteado.", max_digits=12, verbose_name='precio bajo el mínimo'),
        ),
        migrations.AlterField(
            model_name='shippingzone',
            name='carrier_arranged',
            field=models.BooleanField(default=False, help_text="El comprador elige y paga el correo; RaSel no cobra el envío (lo lleva a la sucursal de CABA). Si está activo, se ignoran 'Precio' y 'Gratis desde' y se muestra la leyenda de 'Descripción'.", verbose_name='correo a cargo del comprador'),
        ),
        migrations.AlterField(
            model_name='shippingzone',
            name='cod_allowed',
            field=models.BooleanField(default=False, help_text='Permite pagar en efectivo a contraentrega en esta zona (solo zonas donde RaSel reparte en persona, ej. CABA/AMBA).', verbose_name='acepta efectivo'),
        ),
        migrations.AlterField(
            model_name='shippingzone',
            name='code',
            field=models.SlugField(help_text="Identificador interno, ej. 'free', 'amba', 'national'.", max_length=40, unique=True, verbose_name='código'),
        ),
        migrations.AlterField(
            model_name='shippingzone',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Texto que se muestra en la página de envíos.', verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='shippingzone',
            name='free_over',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Envío gratis a partir de este subtotal de compra. Vacío = siempre gratis (sin mínimo).', max_digits=12, null=True, verbose_name='gratis desde'),
        ),
        migrations.AlterField(
            model_name='shippingzone',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='activa'),
        ),
        migrations.AlterField(
            model_name='shippingzone',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Se aplica cuando el CP no cae en ninguna regla (resto del país).', verbose_name='zona por defecto'),
        ),
        migrations.AlterField(
            model_name='shippingzone',
            name='name',
            field=models.CharField(help_text="Ej. 'CABA y Moreno'.", max_length=80, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='shippingzone',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Costo del envío. 0 = gratis.', max_digits=12, verbose_name='precio'),
        ),
        migrations.AlterField(
            model_name='shippingzone',
            name='sort_order',
            field=models.PositiveIntegerField(default=100, help_text='Orden de prioridad. Menor gana ante rangos superpuestos.', verbose_name='prioridad'),
        ),
    ]
