# Generated by Django 6.0.3 on 2026-07-13 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0010_amba_a_gran_buenos_aires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingzone',
            name='cod_allowed',
            field=models.BooleanField(default=False, help_text='Permite pagar en efectivo a contraentrega en esta zona (solo zonas donde RaSel reparte en persona, ej. CABA/GBA).', verbose_name='acepta efectivo'),
        ),
    ]
