# Generated by Django 5.2.11 on 2026-10-04 15:43

import shipping.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0007_commercialsettings"),
        ("shipping", "0011_alter_shippingzone_cod_allowed"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShippingPromotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Una semana de envío gratis en CABA",
                        max_length=120,
                        verbose_name="título",
                    ),
                ),
                (
                    "introduction",
                    models.TextField(
                        blank=True,
                        default="De nuestro olivar a tu mesa, con envío gratis en CABA.",
                        max_length=1500,
                        verbose_name="introducción",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=160,
                        unique=True,
                        verbose_name="URL permanente",
                    ),
                ),
                (
                    "starts_at",
                    models.DateTimeField(
                        default=shipping.models.promotion_start,
                        verbose_name="inicio (hora argentina)",
                    ),
                ),
                (
                    "ends_at",
                    models.DateTimeField(
                        default=shipping.models.promotion_end,
                        help_text="A partir de este instante vuelve la tarifa habitual. Duración sugerida: siete días corridos.",
                        verbose_name="fin exclusivo (hora argentina)",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(default=False, verbose_name="habilitada"),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="publicada el",
                    ),
                ),
            ],
            options={
                "verbose_name": "promoción de envío",
                "verbose_name_plural": "promociones de envío",
                "ordering": ["-starts_at", "-pk"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("ends_at__gt", models.F("starts_at"))),
                        name="shipping_promotion_valid_dates",
                    )
                ],
            },
        ),
    ]
