# Generated by Django 6.0.3 on 2026-03-06 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_product_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["-name"]},
        ),
        migrations.AlterModelOptions(
            name="variant",
            options={"ordering": ["product__name", "price_ars"]},
        ),
    ]
