# Generated by Django 6.0.3 on 2026-07-03 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_options_alter_variant_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='pack_units',
            field=models.PositiveIntegerField(default=1, help_text='Unidades por caja (1 = no es pack)'),
        ),
        migrations.AddField(
            model_name='variant',
            name='unit_variant',
            field=models.ForeignKey(blank=True, help_text='Variante unitaria equivalente, para calcular el ahorro del pack', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packs', to='shop.variant'),
        ),
    ]
