# Generated by Django 6.0.3 on 2026-07-09 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_variant_pack_units_variant_unit_variant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'categoría', 'verbose_name_plural': 'categorías'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-name'], 'verbose_name': 'producto', 'verbose_name_plural': 'productos'},
        ),
        migrations.AlterModelOptions(
            name='variant',
            options={'ordering': ['product__name', 'price_ars'], 'verbose_name': 'variante', 'verbose_name_plural': 'stock y precios'},
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='activa'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=80, unique=True, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='shop.category', verbose_name='categoría'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='imagen'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='activo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=120, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, max_length=240, verbose_name='descripción corta'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='activa'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='name',
            field=models.CharField(max_length=80, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='pack_units',
            field=models.PositiveIntegerField(default=1, help_text='Unidades por caja (1 = no es pack)', verbose_name='unidades por caja'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='price_ars',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='precio (ARS)'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='shop.product', verbose_name='producto'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='sku',
            field=models.CharField(max_length=64, unique=True, verbose_name='SKU'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='stock_qty',
            field=models.PositiveIntegerField(default=0, verbose_name='stock'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='unit_variant',
            field=models.ForeignKey(blank=True, help_text='Variante unitaria equivalente, para calcular el ahorro del pack', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packs', to='shop.variant', verbose_name='variante unitaria'),
        ),
    ]
