# Generated by Django 5.2.11 on 2026-09-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_alter_category_options_alter_product_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variant",
            name="price_ars",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=12,
                verbose_name="precio de venta (ARS)",
            ),
        ),
        migrations.AddField(
            model_name="variant",
            name="compare_at_price_ars",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text=(
                    "Precio de referencia verdadero de la presentación. Se muestra "
                    "tachado, debe ser mayor al precio de venta y se carga junto con "
                    "el texto de promoción."
                ),
                max_digits=12,
                null=True,
                verbose_name="precio regular (ARS)",
            ),
        ),
        migrations.AddField(
            model_name="variant",
            name="promotion_label",
            field=models.CharField(
                blank=True,
                default="",
                help_text=(
                    "Texto visible en la burbuja, por ejemplo: Precio de lanzamiento "
                    "o Black Friday. Se carga junto con el precio regular."
                ),
                max_length=40,
                verbose_name="texto de promoción",
            ),
        ),
        migrations.AddConstraint(
            model_name="variant",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(("compare_at_price_ars__isnull", True))
                    | models.Q(
                        ("compare_at_price_ars__gt", models.F("price_ars"))
                    )
                ),
                name="shop_variant_compare_at_gt_price",
            ),
        ),
        migrations.AddConstraint(
            model_name="variant",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(
                        ("compare_at_price_ars__isnull", True),
                        ("promotion_label", ""),
                    )
                    | (
                        models.Q(("compare_at_price_ars__isnull", False))
                        & ~models.Q(("promotion_label", ""))
                    )
                ),
                name="shop_variant_promotion_fields_together",
            ),
        ),
    ]
