# Generated by Django 5.2.11 on 2026-09-07 02:04

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DailyTotal",
            fields=[
                ("day", models.DateField(primary_key=True, serialize=False)),
                ("visits", models.PositiveIntegerField(default=0)),
                ("pageviews", models.PositiveIntegerField(default=0)),
                ("cart_added", models.PositiveIntegerField(default=0)),
                ("checkout_opened", models.PositiveIntegerField(default=0)),
                ("checkout_submitted", models.PositiveIntegerField(default=0)),
            ],
            options={
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="Measurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "cleanup_after",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "permissions": [
                    ("view_reports", "Puede consultar reportes de visitas y compras")
                ],
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="Visit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "last_seen_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("day", models.DateField()),
                ("cart_added", models.BooleanField(default=False)),
                ("checkout_opened", models.BooleanField(default=False)),
                ("checkout_submitted", models.BooleanField(default=False)),
            ],
            options={
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="DailyDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.DateField(db_index=True)),
                ("device", models.CharField(max_length=12)),
                ("visits", models.PositiveIntegerField(default=0)),
            ],
            options={
                "default_permissions": (),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("day", "device"), name="analytics_device_day"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DailyProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.DateField(db_index=True)),
                ("product_id", models.PositiveBigIntegerField()),
                ("product_name", models.CharField(max_length=200)),
                ("pageviews", models.PositiveIntegerField(default=0)),
            ],
            options={
                "default_permissions": (),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("day", "product_id"), name="analytics_product_day"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DailySource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.DateField(db_index=True)),
                ("source", models.CharField(max_length=64)),
                ("medium", models.CharField(blank=True, max_length=64)),
                ("campaign", models.CharField(blank=True, max_length=64)),
                ("visits", models.PositiveIntegerField(default=0)),
            ],
            options={
                "default_permissions": (),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("day", "source", "medium", "campaign"),
                        name="analytics_source_day",
                    )
                ],
            },
        ),
    ]
