# Generated by Django 5.2.11 on 2026-09-16 19:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="QualityMeasurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "cleanup_after",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "default_permissions": (),
            },
        ),
        migrations.AddField(
            model_name="dailytotal",
            name="active_visits",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dailytotal",
            name="quality_visits",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="visit",
            name="active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="visit",
            name="quality_version",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.CreateModel(
            name="DailyExclusion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.DateField(db_index=True)),
                ("reason", models.CharField(max_length=20)),
                ("requests", models.PositiveIntegerField(default=0)),
            ],
            options={
                "default_permissions": (),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("day", "reason"), name="analytics_exclusion_day"
                    )
                ],
            },
        ),
    ]
