# Generated by Django 5.2.11 on 2026-02-18 20:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PaymentEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(default="mercadopago", max_length=50)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("topic", models.CharField(blank=True, default="", max_length=50)),
                ("event_id", models.CharField(blank=True, default="", max_length=120)),
                ("resource", models.TextField(blank=True, default="")),
                ("raw", models.JSONField(blank=True, default=dict)),
                ("processed_ok", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, default="")),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
