# Generated by Django 6.0.3 on 2026-06-23 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_paymentdraft_shipping_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdraft',
            name='shipping_carrier_arranged',
            field=models.BooleanField(default=False),
        ),
    ]
