# Generated by Django 6.0.3 on 2026-07-12 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_paymentdraft_delivery_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdraft',
            name='address_extra',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
