# Generated by Django 5.2.11 on 2026-10-04 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0008_paymentdraft_analytics_attributed_at_and_more"),
        ("shipping", "0012_shippingpromotion"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentdraft",
            name="shipping_cost_before_promotion",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                editable=False,
                max_digits=12,
                null=True,
                verbose_name="envío habitual (histórico)",
            ),
        ),
        migrations.AddField(
            model_name="paymentdraft",
            name="shipping_promotion",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="shipping.shippingpromotion",
            ),
        ),
        migrations.AddField(
            model_name="paymentdraft",
            name="shipping_promotion_applied_at",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                null=True,
                verbose_name="beneficio aplicado el",
            ),
        ),
        migrations.AddField(
            model_name="paymentdraft",
            name="shipping_promotion_label",
            field=models.CharField(
                blank=True,
                default="",
                editable=False,
                max_length=120,
                verbose_name="promoción de envío (histórico)",
            ),
        ),
    ]
