# Generated by Django 5.2.11 on 2026-10-04 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0001_initial"),
        ("payments", "0009_paymentdraft_shipping_cost_before_promotion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentdraft",
            name="marketing_captured_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="paymentdraft",
            name="marketing_consent",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="marketing.consent",
            ),
        ),
        migrations.AddField(
            model_name="paymentdraft",
            name="marketing_context",
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name="paymentdraft",
            name="web_checkout_id",
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
